# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[gcloud]
disabled = false
format = '($branch [on $symbol$account(@$domain)(\($project\))]($style) )'
style = "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$shell\
$character
"""

[aws]
format = 'on [$symbol($profile )- ($duration )(\($region\) )]($style)'
style = "bold orange"
symbol = "🅰 "
disabled = true

[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"

[hostname]
ssh_only = true
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = true
show_always = false
